    # **** Setting Socket tunnel ****
- name: Role ensures that the socks tunnel is setup
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ansible-role-event-socks-tunnel
- name: Install and configure Zabbix agent
  hosts: all
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  vars:
      account_code: "{{ hostvars['localhost']['account_code'] }}"
      trans_num: "{{ hostvars['localhost']['trans_num'] }}"
      zabbix_agent_package: "zabbix_agent2-6.0.18-windows-amd64-openssl.msi"
      zabbix_agent_script: "zabbix_agent.ps1"
      zabbix_agent_service_name: "Zabbix Agent 2"

  tasks:
    - name: Copy Zabbix agent package to remote hosts
      win_copy:
        src: "{{ zabbix_agent_package }}"
        dest: "C:\\{{ zabbix_agent_package }}"

    - name: Copy PowerShell script to remote hosts
      win_copy:
        src: "{{ zabbix_agent_script }}"
        dest: "C:\\{{ zabbix_agent_script }}"

    - name: Run PowerShell script to install Zabbix agent
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\\{{ zabbix_agent_script }}
      
    - name: Start Zabbix agent service
      win_service:
        name: "{{ zabbix_agent_service_name }}"
        state: started
