---
- name: "Set API Endpoint URL"
  set_fact:
    api_endpoint: "{{ tower_url }}/api/v2/{{ collection }}/?page_size={{ page_size}}{{ query_args }}"

- name: "Setup Variable To Return Results"
  set_fact:
    collection_results: []

- name: "Get {{ collection }}"
  include_tasks: query_api.yml

- block:
  - name: Ensure output directory exists
    file:
      path: "{{ debug_dir }}"
      state: directory
      mode: '0750'

  - name: Ensure Filename Does Not Contain Slashes
    set_fact:
      collection_filename: "{{ collection | regex_replace('/', '-') }}"

  - name: Save Raw Results
    copy:
      content: "{{ collection_results | to_nice_json }}"
      dest: "{{ debug_dir }}/{{ collection_filename }}_query_results.json"
  when: "(save_raw_results | default(False)) | bool"
