- name: "Retrieve {{ collection }} Details"
  uri:
    url: "{{ api_endpoint }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tower_token }}"
      Content-Type: 'application/json'
    validate_certs: "{{ validate_ssl_cert }}"
  register: api_call_results

- name: "Parse Results"
  set_fact:
    collection_results: "{{ ( collection_results | default([]) ) + api_call_results['json']['results'] }}"
    api_endpoint: "{{ tower_url }}{{ api_call_results['json']['next'] }}"

- name: "Retrieve More {{ collection }} Details"
  include_tasks: query_api.yml
  when: api_call_results['json']['next'] != None and (api_call_results['json']['next'] | length > 0)
