- name: Pull versions file from github if required
  block:
    - name: Set github uri for obtaining versions file
      set_fact:
        versions_file_uri: "https://api.github.kyndryl.net/repos/Continuous-Engineering/ansible_collection_cacf_dev_commontools/contents/roles/ansible-role-cacf_towerinstancerepoupdate/vars/global_event_roles_versions/{{ defaultVersion }}.yml"

    - name: Append branch reference to github uri if needed
      set_fact:
        versions_file_uri: "{{ versions_file_uri }}?ref={{ versionsFileRef }}"
      when: versionsFileRef is defined

    - name: Obtain the versions file from github
      uri:
        url: "{{ versions_file_uri }}"
        headers:
          Authorization: "token {{ lookup('env', 'EVNTINTE_GIT_TOKEN') }}"
      register: versions_file

    - name: Check if versions file was obtained from github
      fail:
        msg: "{{versions_file.status}} : {{ versions_file.msg }}"
      when: versions_file.status != 200

    - name: Set `global_event_roles` from the versions file obtained from github
      block:
        - set_fact:
            decoded_versions: "{{ versions_file.json.content | b64decode | from_yaml }}"
        - set_fact:
            global_event_roles: "{{ decoded_versions.global_event_roles }}"
  when: global_event_roles is undefined

- name: "{{ item.role }} migration"
  towerInstanceRepoUpdate:
    globalOrg: "{{ globalOrg | default('Continuous-Engineering') }}"
    instanceOrg: "{{ TowerInstanceGitHubOrg }}"
    roleName: "{{ item.role }}"
    versionName: "{{ item.version | default(hostvars['localhost']['defaultVersion']) }}"
  with_items: "{{ global_event_roles }}"
